"""
Base class for all trading agents.
Defines the common interface and shared functionality.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Any
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from loguru import logger


class Action(Enum):
    """Trading actions."""
    HOLD = 0
    BUY = 1
    SELL = 2


@dataclass
class Signal:
    """
    Trading signal generated by an agent.

    Attributes:
        symbol: Asset symbol
        action: Trading action (BUY, SELL, HOLD)
        confidence: Confidence level [0, 1]
        position_size: Suggested position size as fraction of portfolio [0, 1]
        timestamp: When signal was generated
        agent_name: Name of the agent that generated this signal
        metadata: Additional information (reasoning, features used, etc.)
    """
    symbol: str
    action: Action
    confidence: float
    position_size: float
    timestamp: datetime
    agent_name: str
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        # Validate confidence is in [0, 1]
        self.confidence = np.clip(self.confidence, 0.0, 1.0)
        # Validate position size is in [0, 1]
        self.position_size = np.clip(self.position_size, 0.0, 1.0)

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "action": self.action.name,
            "confidence": self.confidence,
            "position_size": self.position_size,
            "timestamp": self.timestamp.isoformat(),
            "agent_name": self.agent_name,
            "metadata": self.metadata,
        }

    @property
    def is_actionable(self) -> bool:
        """Check if signal suggests taking action (not HOLD)."""
        return self.action != Action.HOLD and self.confidence > 0.5


@dataclass
class AgentState:
    """
    Internal state of an agent.
    Used for stateful agents (Liquid NN, Mamba) that maintain memory.
    """
    hidden_state: Optional[torch.Tensor] = None
    memory: Optional[torch.Tensor] = None
    step_count: int = 0
    last_signal: Optional[Signal] = None

    def reset(self):
        """Reset state to initial values."""
        self.hidden_state = None
        self.memory = None
        self.step_count = 0
        self.last_signal = None


class BaseAgent(ABC):
    """
    Abstract base class for all trading agents.

    All agents must implement:
    - predict(): Generate trading signal from market data
    - get_feature_names(): Return list of required features

    Optional overrides:
    - update(): Online learning/adaptation
    - reset(): Reset internal state
    - save/load(): Model persistence
    """

    def __init__(
        self,
        name: str,
        input_dim: int,
        device: str = "auto",
        seed: int = 42,
    ):
        """
        Initialize base agent.

        Args:
            name: Unique identifier for this agent
            input_dim: Dimension of input features
            device: Device for computation ('cpu', 'cuda', or 'auto')
            seed: Random seed for reproducibility
        """
        self.name = name
        self.input_dim = input_dim
        self.seed = seed
        self.logger = logger.bind(agent=name)

        # Set device
        if device == "auto":
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = torch.device(device)

        # Set random seeds
        torch.manual_seed(seed)
        np.random.seed(seed)

        # Initialize state
        self.state = AgentState()
        self.is_trained = False
        self.model: Optional[nn.Module] = None

        self.logger.info(f"Initialized {name} on {self.device}")

    @abstractmethod
    def predict(
        self,
        features: pd.DataFrame | np.ndarray | torch.Tensor,
        symbol: str,
    ) -> Signal:
        """
        Generate trading signal from market features.

        Args:
            features: Market features (technical indicators, etc.)
            symbol: Asset symbol being analyzed

        Returns:
            Signal object with trading recommendation
        """
        pass

    @abstractmethod
    def get_feature_names(self) -> list[str]:
        """
        Get list of feature names required by this agent.

        Returns:
            List of feature column names
        """
        pass

    def preprocess(
        self,
        features: pd.DataFrame | np.ndarray | torch.Tensor,
    ) -> torch.Tensor:
        """
        Preprocess features into tensor format.

        Args:
            features: Raw features in various formats

        Returns:
            Preprocessed tensor on correct device
        """
        if isinstance(features, pd.DataFrame):
            # Select only required features if available
            required = self.get_feature_names()
            available = [f for f in required if f in features.columns]
            if len(available) < len(required):
                missing = set(required) - set(available)
                self.logger.warning(f"Missing features: {missing}")
            features = features[available].values

        if isinstance(features, np.ndarray):
            features = torch.FloatTensor(features)

        # Handle NaN values
        features = torch.nan_to_num(features, nan=0.0)

        # Ensure correct shape (batch_size, seq_len, features) or (batch_size, features)
        if features.dim() == 1:
            features = features.unsqueeze(0)  # Add batch dimension

        return features.to(self.device)

    def update(
        self,
        features: torch.Tensor,
        reward: float,
        done: bool = False,
    ) -> dict[str, float]:
        """
        Online update/adaptation (optional).
        Override for agents that learn during inference.

        Args:
            features: Latest market features
            reward: Reward signal (e.g., return from last action)
            done: Whether episode is complete

        Returns:
            Dictionary of metrics (loss, etc.)
        """
        return {}

    def reset(self):
        """Reset agent's internal state."""
        self.state.reset()
        self.logger.debug("Agent state reset")

    def train_mode(self):
        """Set agent to training mode."""
        if self.model is not None:
            self.model.train()

    def eval_mode(self):
        """Set agent to evaluation mode."""
        if self.model is not None:
            self.model.eval()

    def save(self, path: str):
        """
        Save agent state to disk.

        Args:
            path: File path for saved state
        """
        if self.model is None:
            self.logger.warning("No model to save")
            return

        state_dict = {
            "model_state": self.model.state_dict(),
            "name": self.name,
            "input_dim": self.input_dim,
            "is_trained": self.is_trained,
            "config": self.get_config(),
        }
        torch.save(state_dict, path)
        self.logger.info(f"Saved agent to {path}")

    def load(self, path: str):
        """
        Load agent state from disk.

        Args:
            path: File path to load from
        """
        if self.model is None:
            self.logger.error("Model not initialized")
            return

        state_dict = torch.load(path, map_location=self.device)
        self.model.load_state_dict(state_dict["model_state"])
        self.is_trained = state_dict.get("is_trained", True)
        self.logger.info(f"Loaded agent from {path}")

    def get_config(self) -> dict:
        """Get agent configuration for serialization."""
        return {
            "name": self.name,
            "input_dim": self.input_dim,
            "device": str(self.device),
            "seed": self.seed,
        }

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name}, input_dim={self.input_dim})"


class BaseNeuralAgent(BaseAgent):
    """
    Base class for neural network-based agents.
    Provides common training loop and optimization utilities.
    """

    def __init__(
        self,
        name: str,
        input_dim: int,
        hidden_dim: int = 128,
        num_layers: int = 2,
        dropout: float = 0.1,
        learning_rate: float = 1e-4,
        **kwargs,
    ):
        super().__init__(name, input_dim, **kwargs)

        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        self.dropout = dropout
        self.learning_rate = learning_rate

        self.optimizer: Optional[torch.optim.Optimizer] = None
        self.scheduler: Optional[torch.optim.lr_scheduler._LRScheduler] = None
        self.loss_fn: Optional[nn.Module] = None

    def setup_optimizer(self, optimizer_class=torch.optim.AdamW, **kwargs):
        """Configure optimizer for training."""
        if self.model is None:
            raise ValueError("Model not initialized")

        self.optimizer = optimizer_class(
            self.model.parameters(),
            lr=self.learning_rate,
            **kwargs,
        )
        self.logger.debug(f"Optimizer configured: {optimizer_class.__name__}")

    def setup_scheduler(self, scheduler_class, **kwargs):
        """Configure learning rate scheduler."""
        if self.optimizer is None:
            raise ValueError("Optimizer not initialized")

        self.scheduler = scheduler_class(self.optimizer, **kwargs)

    def training_step(
        self,
        batch: dict[str, torch.Tensor],
    ) -> dict[str, float]:
        """
        Single training step.

        Args:
            batch: Dictionary with 'features', 'targets', etc.

        Returns:
            Dictionary of metrics
        """
        if self.model is None or self.optimizer is None:
            raise ValueError("Model or optimizer not initialized")

        self.model.train()
        self.optimizer.zero_grad()

        # Forward pass
        features = batch["features"].to(self.device)
        targets = batch["targets"].to(self.device)

        outputs = self.model(features)
        loss = self.loss_fn(outputs, targets)

        # Backward pass
        loss.backward()

        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)

        self.optimizer.step()

        if self.scheduler is not None:
            self.scheduler.step()

        return {"loss": loss.item()}

    def get_config(self) -> dict:
        config = super().get_config()
        config.update({
            "hidden_dim": self.hidden_dim,
            "num_layers": self.num_layers,
            "dropout": self.dropout,
            "learning_rate": self.learning_rate,
        })
        return config


# Standard feature sets that agents can use
CORE_FEATURES = [
    "returns", "log_returns",
    "rsi_14", "macd", "macd_signal",
    "bb_position", "atr_pct",
    "volume_ratio", "obv",
]

MOMENTUM_FEATURES = [
    "rsi_14", "rsi_21",
    "stoch_k", "stoch_d",
    "roc_5", "roc_10", "roc_20",
    "momentum_10", "momentum_20",
    "williams_r", "cci",
]

TREND_FEATURES = [
    "sma_20_50_cross", "sma_50_200_cross",
    "price_sma_20_ratio", "price_sma_50_ratio", "price_sma_200_ratio",
    "macd", "macd_signal", "macd_histogram",
]

VOLATILITY_FEATURES = [
    "atr_14", "atr_pct",
    "bb_width", "bb_position",
    "volatility_10d", "volatility_20d", "volatility_ratio",
]

ALL_FEATURES = list(set(
    CORE_FEATURES + MOMENTUM_FEATURES + TREND_FEATURES + VOLATILITY_FEATURES
))
